theme: jekyll-theme-dinky
title: SME(FT) - Skyrim Modding Essentials (Fixes & Tools)
description: A resource for a ready to mod Skyrim setup in ~10 minutes.
show_downloads: true
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
github:
  modlistrelases_url: https://github.com/EzioTheDeadPoet/SME-FT-/releases
  modlist_url: https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/releases/download/v1.0/Tales.from.Skyrim.s.Holds.wabbajack
pages:
  mainpage_url: https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/
  screenshots_url: https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/SCREENSHOTSDISPLAY.html
  contribute_url: https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/HOWTOCONTRIBUTE.html
  changelog_url: https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/CHANGELOG.html
reshade:
  license: https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/ReShade/RESHADELICENSE.html
